# configs/example_inputs.yaml
inputs:
  - name: speed_inorg
    label: "Speed (Inorg) [m/min]"
    unit: "m/min"
    kind: grid
    start: 0.25
    stop: 1.00
    step: 0.01
    decimals: 4

  - name: speed_org
    label: "Speed (Org) [m/min]"
    unit: "m/min"
    kind: grid
    start: 0.25
    stop: 1.00
    step: 0.01
    decimals: 4

  - name: inkfl_inorg
    label: "inkFL (Inorg) [uL/min]"
    unit: "uL/min"
    kind: grid
    start: 80
    stop: 240
    step: 1

  - name: inkfl_org
    label: "inkFL (Org) [uL/min]"
    unit: "uL/min"
    kind: grid
    start: 100
    stop: 280
    step: 1

  - name: conc_inorg
    label: "Conc. (Inorg) [M]"
    unit: "M"
    kind: grid
    start: 0.8
    stop: 1.4
    step: 0.05

  - name: conc_org
    label: "Conc. (Org) [M]"
    unit: "M"
    kind: grid
    start: 0.4
    stop: 1.2
    step: 0.05

  - name: absolute_humidity
    label: "AH [g/m^3]"
    unit: "g/m^3"
    kind: grid
    start: 2
    stop: 37
    step: 1

  - name: temperature_c
    label: "Temp [C]"
    unit: "C"
    kind: grid
    start: 20
    stop: 50
    step: 1

objectives:
  names: ["PCE", "Stability", "Repeatability"]

constraints:
  clausius_clapeyron: true
  ah_col: "absolute_humidity"
  temp_c_col: "temperature_c"
